// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ4m3sHW0R5F2PHbns9NVRliBBMT0kDFA',
    appId: '1:812773951106:web:56b6b4227f30181e1f969b',
    messagingSenderId: '812773951106',
    projectId: 'nurses-todo-app',
    authDomain: 'nurses-todo-app.firebaseapp.com',
    storageBucket: 'nurses-todo-app.appspot.com',
    measurementId: 'G-1XNZRX5HRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9BO9vn1xl4IT5CE5tcvv48mADgI_2KSY',
    appId: '1:812773951106:android:4ddec1583daa2b0b1f969b',
    messagingSenderId: '812773951106',
    projectId: 'nurses-todo-app',
    storageBucket: 'nurses-todo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARDklk0pgQQwbLY1dp76xYGad5iaO0_9g',
    appId: '1:812773951106:ios:474a1a07c005a4a91f969b',
    messagingSenderId: '812773951106',
    projectId: 'nurses-todo-app',
    storageBucket: 'nurses-todo-app.appspot.com',
    androidClientId:
        '812773951106-1ohpgcf083u056i2929u90soensb29f2.apps.googleusercontent.com',
    iosClientId:
        '812773951106-6imuahnluglnlicjbjuki9aguo2uek17.apps.googleusercontent.com',
    iosBundleId: 'com.example.nursesTodoApp',
  );
}
